#!/usr/bin/python

import lib.utils as utils
from tendo import singleton
import argparse
import random

me = singleton.SingleInstance() # will sys.exit(-1) if other instance is running

parser = argparse.ArgumentParser(description='Sends testing random data to server.')

parser.add_argument('-s', '--send',    action="store_true", help='Send to server, otherwise just test.')
parser.add_argument('-v', '--verbose', action="store_true", help='Print out more info.')

args = parser.parse_args()

test_data = random.random() * 50
if (args.verbose):
    print "Data to send: " + str(test_data)
if (args.send):
    utils.send_to_cloud("temp", test_data)
